on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: windows-latest
    name: Generate C# Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.300"
      - name: C# Documentation Generator
        uses: FuLagann/csharp-docs-generator@v1.0
        with:
          build-tasks: dotnet build
          cleanup-tasks: dotnet clean, cp -rf docs/api/* ., ls --la ./index.html
          binaries: Clockify.Net\bin\Debug\netstandard2.0\Clockify.Net.dll
          output-path: docs/api
          branch-name: gh-pages
          user-email: morasiu2@gmail.com
          user-name: Morasiu
          project-details-json: project-details.json
